# Generated by Django 4.0.4 on 2022-04-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='disc_price',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(default='default.jpg', null=True, upload_to='product'),
        ),
    ]
