# Generated by Django 4.0.4 on 2022-04-27 15:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
        ('product', '0003_remove_products_disc_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artist.artist'),
        ),
        migrations.AddField(
            model_name='products',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
