# Generated by Django 4.0.4 on 2022-04-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_products_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='offer',
            field=models.CharField(choices=[('first', '10'), ('second', '15'), ('third', '20'), ('fourth', '22'), ('fifth', '25')], default='10', max_length=20, null=True),
        ),
    ]
