# Generated by Django 4.0.4 on 2022-04-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_rename_custometr_cart_customer_remove_cart_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
