# Generated by Django 4.0.4 on 2022-04-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Book', 'Book'), ('Dis', 'Dispatch'), ('Del', 'Delivered')], default='Add to cart', max_length=20, null=True),
        ),
    ]
